title: Documentation
theme: just-the-docs
username: ProgrammEverything
description: Documentation for all ProgrammEverything's projects
email: sasanxcoder@gmail.com
name: Sasan salehi
repo: documentation
title: Documentation
url: https://ProgrammEverything.github.io
favicon_ico: "/assets/default/images/favicon.ico"
aux_links:
  Repository: "https://github.com/ProgrammEverything/documentation" 
  Github page: "https://github.com/ProgrammEverything"
aux_links_new_tab: true
color_scheme: dark
